# Copyright 2025-2026 Sutharsan
# SPDX-License-Identifier: Apache-2.0

"""YAML export for Nav2 parameter values.

Generates a nav2_params.yaml string from live ParamValue objects, grouped by
node with ros__parameters nesting.  Adds description comments above any
parameter whose value has been changed from its schema default.
"""

from __future__ import annotations

from typing import Any

from nav2_config.types.params import ParamValue


# ---------------------------------------------------------------------------
# Value formatting
# ---------------------------------------------------------------------------

def _format_value(value: Any) -> str:
    """Format a Python value as a YAML scalar or inline sequence.

    Args:
        value: Python native value (bool, int, float, str, list).

    Returns:
        YAML-safe string representation.
    """
    if isinstance(value, bool):
        # bool must be checked before int since bool is a subclass of int.
        return 'true' if value else 'false'
    if isinstance(value, float):
        # repr gives enough precision without trailing noise.
        s = repr(value)
        if '.' not in s and 'e' not in s.lower():
            s += '.0'
        return s
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        items = ', '.join(_format_value(v) for v in value)
        return f'[{items}]'
    if isinstance(value, str):
        # Quote strings that contain characters special to YAML scalars.
        needs_quotes = any(c in value for c in (':', '#', '[', ']', '{', '}', ',', '&', '*', '?', '|', '<', '>', '=', '!', '%', '@', '`'))
        needs_quotes = needs_quotes or (value and value[0] in ('"', "'", '-', '~', '>'))
        if needs_quotes:
            escaped = value.replace('\\', '\\\\').replace('"', '\\"')
            return f'"{escaped}"'
        return value if value else '""'
    return str(value)


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _node_path_to_yaml_keys(node_path: str) -> list[str]:
    """Map a ROS2 node path to the YAML key list ending with 'ros__parameters'.

    Examples::

        '/controller_server'           -> ['controller_server', 'ros__parameters']
        '/robot1/controller_server'    -> ['robot1', 'controller_server', 'ros__parameters']
        '/local_costmap/local_costmap' -> ['local_costmap', 'local_costmap', 'ros__parameters']

    Args:
        node_path: Full ROS2 node path, e.g. ``'/robot1/controller_server'``.

    Returns:
        List of YAML key components ending with ``'ros__parameters'``.
    """
    bare = node_path.lstrip('/')
    parts = [p for p in bare.split('/') if p]
    return parts + ['ros__parameters']


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_yaml(
    params: list[ParamValue],
    ros_version: str = "humble",
    plugin_filter: str | None = None,
    pending_params: set[str] | None = None,
) -> str:
    """Generate a nav2_params.yaml string from live parameter values.

    Parameters are grouped by node name under ``ros__parameters``.
    A comment line is inserted above each parameter whose ``current_value``
    differs from the schema default, explaining its purpose and tuning impact.
    Parameters in *pending_params* get an inline ``# (pending)`` marker so the
    YAML panel can highlight them in blue.

    Args:
        params: Live parameter values to export.
        ros_version: ROS2 distro name written into the file header.
        plugin_filter: When set, only params with ``plugin_specific=False`` or
            whose ``plugin`` field equals this value are included.
        pending_params: Set of param names whose values have been edited in the
            GUI but not yet sent to the ROS2 node.

    Returns:
        A YAML string suitable for use as ``nav2_params.yaml``.
    """
    pending: set[str] = pending_params or set()

    # Apply plugin filter.
    visible: list[ParamValue] = []
    for pv in params:
        defn = pv.definition
        if plugin_filter is not None and defn.plugin_specific and defn.plugin != plugin_filter:
            continue
        visible.append(pv)

    lines: list[str] = [
        "# Generated by nav2_config",
        f"# ROS2 {ros_version}",
        "",
    ]

    if not visible:
        lines.append("# (no parameters to export)")
        return "\n".join(lines) + "\n"

    # Group by full node path, preserving alphabetical order.
    by_node: dict[str, list[ParamValue]] = {}
    for pv in visible:
        node_key = pv.node_path if pv.node_path else f"/{pv.definition.node}"
        by_node.setdefault(node_key, []).append(pv)

    for node_key in sorted(by_node):
        keys = _node_path_to_yaml_keys(node_key)
        # Emit nested YAML structure: each key except the last on its own line.
        for depth, key in enumerate(keys[:-1]):
            indent = "  " * depth
            lines.append(f"{indent}{key}:")
        # ros__parameters line
        ros_indent = "  " * (len(keys) - 1)
        lines.append(f"{ros_indent}ros__parameters:")

        # Parameter indent is one level deeper than ros__parameters.
        param_indent = "  " * len(keys)
        node_params = sorted(by_node[node_key], key=lambda p: p.definition.param)
        for pv in node_params:
            defn = pv.definition
            if pv.is_modified and defn.description:
                # Build a single-line comment explaining what this param does.
                comment = defn.description.rstrip('.')
                if defn.impact:
                    comment += f".  {defn.impact}"
                # Wrap long comments at ~100 chars using continuation lines.
                if len(comment) > 100:
                    comment = comment[:97] + '...'
                lines.append(f"{param_indent}# {comment}")
            value_line = f"{param_indent}{defn.param}: {_format_value(pv.current_value)}"
            if defn.param in pending:
                value_line += "  # (pending)"
            lines.append(value_line)

        lines.append("")  # Blank line between nodes.

    return "\n".join(lines)


def save_yaml_to_file(yaml_str: str, filepath: str) -> None:
    """Write a YAML string to a file.

    Args:
        yaml_str: YAML content to write.
        filepath: Destination file path.

    Raises:
        OSError: If the file cannot be written.
    """
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(yaml_str)
